### ISSUE TITLE
 Seqlevels problem

### ISSUE THREAD

**Issue by msAn-korea** [igchoi/IBT618-SystemsBiotechnology#3]
# problem
둘 모두  Zobellia galactanivorans DsijT로 같은 strain이지만, seqlevels이 일치가 되지 않아  R에서 alignment이 되지 않습니다.
======
# file list
사용하고자 하는 sample list입니다.
GSM5699202: Free-living cells with maltose rep 1; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191408[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191408%5Baccn%5D)
GSM5699203: Free-living cells with maltose rep 2; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191409[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191409%5Baccn%5D)
GSM5699204: Free-living cells with maltose rep 3; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191410[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191410%5Baccn%5D)
GSM5699196: Free-living cells with alginate rep 1; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191402[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191402%5Baccn%5D)
GSM5699197: Free-living cells with alginate rep 2; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191403[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191403%5Baccn%5D)
GSM5699198: Free-living cells with alginate rep 3; Zobellia galactanivorans; RNA-Seq
[https://www.ncbi.nlm.nih.gov/sra/SRX13191404[accn]](https://www.ncbi.nlm.nih.gov/sra/SRX13191404%5Baccn%5D)

reference genome으로 사용한 링크입니다.
https://www.ncbi.nlm.nih.gov/nuccore/NC_015844.1

# Soultion 

HISAT2 can be used to solve this.

**Comment by igchoi** [comment]
1. "seqlevels"이 무엇인지 이해하면 쉽게 해결가능
2. https://bioconductor.org/packages/devel/bioc/vignettes/GenomicFeatures/inst/doc/GenomicFeatures.html
