### ISSUE TITLE
DEG problem

### ISSUE THREAD

**Issue by msAn-korea** [igchoi/IBT618-SystemsBiotechnology#4]
# script
DEG
dge.glm = estimateGLMCommonDisp(dge, design)
fit = glmFit(dge.glm, design,dispersion=dge.glm$common.dispersion)

# console

DEG
> dge.glm = estimateGLMCommonDisp(dge, design)
경고메시지(들): 
estimateGLMCommonDisp.default(y = y$counts, design = design, 에서:
  No residual df: setting dispersion to NA
> fit = glmFit(dge.glm, design,dispersion=dge.glm$common.dispersion)
glmFit.default(y = y$counts, design = design, dispersion = dispersion, 에서 다음과 같은 에러가 발생했습니다:
  NA dispersions not allowed

**Comment by igchoi** [comment]
1. replicate 지정(디자인)이 잘못되었거나 전체 데이터에서 특정 시료/유전자의 값이이 누락된 경우
2. 다른 예 참고 https://github.com/tgirke/systemPipeR/issues/4
