### ISSUE TITLE
CIRCexplorer2 

### ISSUE THREAD

**Issue by igchoi** [igchoi/IBT618-SystemsBiotechnology#7]
@Taeheon-L you can use it in the EU Galaxy server..

[USA server (usegalaxy.org)](https://usegalaxy.org/) does not provide CIRCexplorer2 but [EU server (usegalaxy.eu)](https://usegalaxy.eu/) has [this tool](https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fcircexplorer2%2Fcircexplorer2%2F2.3.8%2Bgalaxy0&version=latest).

**Comment by Taeheon-L** [comment]
이걸로 진행해보겠습니다.
감사합니다 교수님.

이태헌 올림 

-----Original Message-----
From: "In-Geol ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>; ***@***.***>;
Sent: 2024. 6. 5. (수) 18:59 (GMT+09:00)
Subject: [igchoi/IBT618-SystemsBiotechnology] CIRCexplorer2 (Issue #7)

@Taeheon-L you can use it in the EU Galaxy server..
USA server (usegalaxy.org) does not provide CIRCexplorer2 but EU server (usegalaxy.eu) has this tool.

**Comment by igchoi** [comment]
Galaxy workflow by CSBL
https://usegalaxy.org.au/u/csbl/w/unnamed-workflow
